### ISSUE TITLE
Bot token compromised

### ISSUE THREAD

**Issue by myrkvi** [1Revenger1/Dragonite#9]
Hi! As of 20:05 UTC there was an announcement in a moderation server that a bot with the name "Dragonite" had had its token compromised. I apologise in advance if this is a bad way of communicating it to you, but I found no contact information on your GitHub user.

![Screenshot of message](https://i.imgur.com/4QeyAXI.png)
*Screenshot of a Discord message: @everyone Dragonite bot has been compromised and was raiding servers due to a leaked token. If you have dragonite on your server, you might want to kill its perms until the issue is resolved. It's deleting chatrooms, stripping roles, all kinds of nasty stuff.*

I hope the issue will be resolved, and I'd love to hear back when it is, so that I can forward it.

**Comment by hook54321** [comment]
Token has already been changed

**Comment by 1Revenger1** [comment]
Thanks for that. I unfortunately was on a plane down to California while this occurred. I have since changed the Token, and have tested my one handed keyboarding typing skills while walking out of an airport

**Comment by myrkvi** [comment]
Okay, thank you! I'll pass it on.

**Comment by 1Revenger1** [comment]
Thanks for being understanding lol. It was my stupidity that caused this to happen, and is something that I really should've changed a while ago and never thought about. If you need any sort of help, Discord tag is "1Revenger1#2952"
